// AUTO-GENERATED by scripts/deploy.ts after deployment.
// Before deploying, CONTRACT_ADDRESS is empty — the app uses mock data.
// After `npm run deploy:sepolia`, this file is overwritten with real address + ABI.

export const CONTRACT_ADDRESS =
  (process.env.NEXT_PUBLIC_CONTRACT_ADDRESS as string) ?? "";

export const CONTRACT_ABI = [
  // createProposal
  {
    "type": "function",
    "name": "createProposal",
    "inputs": [
      { "name": "_title",       "type": "string"  },
      { "name": "_description", "type": "string"  },
      { "name": "_durationSec", "type": "uint256" },
      { "name": "_quorum",      "type": "uint256" }
    ],
    "outputs": [{ "name": "", "type": "uint256" }],
    "stateMutability": "nonpayable"
  },
  // vote
  {
    "type": "function",
    "name": "vote",
    "inputs": [
      { "name": "_proposalId", "type": "uint256" },
      { "name": "_choice",     "type": "uint8"   }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  // getAllProposals
  {
    "type": "function",
    "name": "getAllProposals",
    "inputs": [],
    "outputs": [
      { "name": "ids",        "type": "uint256[]" },
      { "name": "titles",     "type": "string[]"  },
      { "name": "creators",   "type": "address[]" },
      { "name": "yesArr",     "type": "uint256[]" },
      { "name": "noArr",      "type": "uint256[]" },
      { "name": "abstainArr", "type": "uint256[]" },
      { "name": "endTimes",   "type": "uint256[]" },
      { "name": "statuses",   "type": "uint8[]"   }
    ],
    "stateMutability": "view"
  },
  // getProposal
  {
    "type": "function",
    "name": "getProposal",
    "inputs": [{ "name": "_id", "type": "uint256" }],
    "outputs": [
      { "name": "id",           "type": "uint256" },
      { "name": "title",        "type": "string"  },
      { "name": "description",  "type": "string"  },
      { "name": "creator",      "type": "address" },
      { "name": "startTime",    "type": "uint256" },
      { "name": "endTime",      "type": "uint256" },
      { "name": "quorum",       "type": "uint256" },
      { "name": "yesVotes",     "type": "uint256" },
      { "name": "noVotes",      "type": "uint256" },
      { "name": "abstainVotes", "type": "uint256" },
      { "name": "status",       "type": "uint8"   }
    ],
    "stateMutability": "view"
  },
  // getVote
  {
    "type": "function",
    "name": "getVote",
    "inputs": [
      { "name": "_voter",      "type": "address" },
      { "name": "_proposalId", "type": "uint256" }
    ],
    "outputs": [{ "name": "", "type": "uint8" }],
    "stateMutability": "view"
  },
  // proposalCount
  {
    "type": "function",
    "name": "proposalCount",
    "inputs": [],
    "outputs": [{ "name": "", "type": "uint256" }],
    "stateMutability": "view"
  },
  // Events
  {
    "type": "event",
    "name": "ProposalCreated",
    "inputs": [
      { "name": "id",        "type": "uint256", "indexed": true  },
      { "name": "creator",   "type": "address", "indexed": true  },
      { "name": "title",     "type": "string",  "indexed": false },
      { "name": "startTime", "type": "uint256", "indexed": false },
      { "name": "endTime",   "type": "uint256", "indexed": false },
      { "name": "quorum",    "type": "uint256", "indexed": false }
    ]
  },
  {
    "type": "event",
    "name": "Voted",
    "inputs": [
      { "name": "proposalId", "type": "uint256", "indexed": true  },
      { "name": "voter",      "type": "address", "indexed": true  },
      { "name": "choice",     "type": "uint8",   "indexed": false }
    ]
  }
] as const;
