import hre from "hardhat";
const { ethers } = hre;
import fs from "fs";
import path from "path";

async function main() {
  console.log("🚀 Deploying ChainVotes to Sepolia...\n");

  const [deployer] = await ethers.getSigners();
  console.log("📍 Deployer address:", deployer.address);

  const balance = await ethers.provider.getBalance(deployer.address);
  console.log("💰 Balance:", ethers.formatEther(balance), "ETH\n");

  if (balance === 0n) {
    throw new Error("❌ Deployer has 0 ETH. Get testnet ETH from https://sepoliafaucet.com");
  }

  const ChainVotes = await ethers.getContractFactory("ChainVotes");
  console.log("📝 Deploying contract...");
  const contract = await ChainVotes.deploy();
  await contract.waitForDeployment();

  const address = await contract.getAddress();
  console.log("\n✅ ChainVotes deployed!");
  console.log("📋 Contract address:", address);
  console.log(`🔍 View on Etherscan: https://sepolia.etherscan.io/address/${address}\n`);

  // ─── Seed 3 demo proposals ───────────────────────────────────────────────
  console.log("🌱 Seeding demo proposals...\n");

  const DAY = 86400n;
  const demos = [
    {
      title: "Upgrade Treasury Multi-sig to 5/9",
      description:
        "Proposal to increase treasury multi-signature threshold from 3/7 to 5/9 for enhanced security of protocol funds. This change will require consensus from 5 out of 9 signers before any fund movement.",
      duration: DAY * 3n,
      quorum: 500n,
    },
    {
      title: "Enable Cross-chain Bridge to Arbitrum",
      description:
        "Deploy official bridge contract enabling seamless asset transfers between Sepolia and Arbitrum One testnet. Reduces friction for multi-chain operations and improves developer experience.",
      duration: DAY * 7n,
      quorum: 500n,
    },
    {
      title: "Allocate 500 ETH to Dev Fund Q2",
      description:
        "Release 500 ETH from the protocol treasury to fund development activities for Q2 roadmap milestones including ZK rollup integration and new SDK release.",
      duration: DAY * 14n,
      quorum: 400n,
    },
  ];

  for (const d of demos) {
    const tx = await contract.createProposal(d.title, d.description, d.duration, d.quorum);
    const receipt = await tx.wait();
    console.log(`  ✓ "${d.title.slice(0, 40)}..." — tx: ${receipt?.hash}`);
  }

  // ─── Write contract address to env & lib ────────────────────────────────
  const envPath = path.join(__dirname, "..", ".env.local");
  let envContent = "";
  if (fs.existsSync(envPath)) {
    envContent = fs.readFileSync(envPath, "utf8");
    // Remove old CONTRACT_ADDRESS line if exists
    envContent = envContent.replace(/^NEXT_PUBLIC_CONTRACT_ADDRESS=.*/m, "");
  }
  envContent += `\nNEXT_PUBLIC_CONTRACT_ADDRESS=${address}\n`;
  fs.writeFileSync(envPath, envContent.trim() + "\n");
  console.log(`\n📄 .env.local updated with NEXT_PUBLIC_CONTRACT_ADDRESS=${address}`);

  // Write ABI to lib/contract.ts
  const artifactPath = path.join(
    __dirname,
    "..",
    "artifacts",
    "contracts",
    "ChainVotes.sol",
    "ChainVotes.json"
  );
  const artifact = JSON.parse(fs.readFileSync(artifactPath, "utf8"));
  const libContent = `// AUTO-GENERATED by scripts/deploy.ts — do not edit manually
export const CONTRACT_ADDRESS = "${address}" as const;
export const CONTRACT_ABI = ${JSON.stringify(artifact.abi, null, 2)} as const;
`;
  fs.writeFileSync(path.join(__dirname, "..", "lib", "contract.ts"), libContent);
  console.log("📄 lib/contract.ts generated with ABI + address\n");

  console.log("🎉 Done! Run `npm run dev` and your dApp is live on Sepolia.");
}

main().catch((err) => {
  console.error("❌ Deploy failed:", err);
  process.exit(1);
});
