/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export interface ChainVotesInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "createProposal"
      | "getAllProposals"
      | "getProposal"
      | "getVote"
      | "proposalCount"
      | "proposals"
      | "vote"
      | "votes"
  ): FunctionFragment;

  getEvent(nameOrSignatureOrTopic: "ProposalCreated" | "Voted"): EventFragment;

  encodeFunctionData(
    functionFragment: "createProposal",
    values: [string, string, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getAllProposals",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getProposal",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getVote",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "proposalCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "proposals",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "vote",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "votes",
    values: [AddressLike, BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "createProposal",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getAllProposals",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getProposal",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getVote", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "proposalCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "proposals", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "vote", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "votes", data: BytesLike): Result;
}

export namespace ProposalCreatedEvent {
  export type InputTuple = [
    id: BigNumberish,
    creator: AddressLike,
    title: string,
    startTime: BigNumberish,
    endTime: BigNumberish,
    quorum: BigNumberish
  ];
  export type OutputTuple = [
    id: bigint,
    creator: string,
    title: string,
    startTime: bigint,
    endTime: bigint,
    quorum: bigint
  ];
  export interface OutputObject {
    id: bigint;
    creator: string;
    title: string;
    startTime: bigint;
    endTime: bigint;
    quorum: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace VotedEvent {
  export type InputTuple = [
    proposalId: BigNumberish,
    voter: AddressLike,
    choice: BigNumberish
  ];
  export type OutputTuple = [proposalId: bigint, voter: string, choice: bigint];
  export interface OutputObject {
    proposalId: bigint;
    voter: string;
    choice: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface ChainVotes extends BaseContract {
  connect(runner?: ContractRunner | null): ChainVotes;
  waitForDeployment(): Promise<this>;

  interface: ChainVotesInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  createProposal: TypedContractMethod<
    [
      _title: string,
      _description: string,
      _durationSec: BigNumberish,
      _quorum: BigNumberish
    ],
    [bigint],
    "nonpayable"
  >;

  getAllProposals: TypedContractMethod<
    [],
    [
      [
        bigint[],
        string[],
        string[],
        bigint[],
        bigint[],
        bigint[],
        bigint[],
        bigint[]
      ] & {
        ids: bigint[];
        titles: string[];
        creators: string[];
        yesArr: bigint[];
        noArr: bigint[];
        abstainArr: bigint[];
        endTimes: bigint[];
        statuses: bigint[];
      }
    ],
    "view"
  >;

  getProposal: TypedContractMethod<
    [_id: BigNumberish],
    [
      [
        bigint,
        string,
        string,
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint
      ] & {
        id: bigint;
        title: string;
        description: string;
        creator: string;
        startTime: bigint;
        endTime: bigint;
        quorum: bigint;
        yesVotes: bigint;
        noVotes: bigint;
        abstainVotes: bigint;
        status: bigint;
      }
    ],
    "view"
  >;

  getVote: TypedContractMethod<
    [_voter: AddressLike, _proposalId: BigNumberish],
    [bigint],
    "view"
  >;

  proposalCount: TypedContractMethod<[], [bigint], "view">;

  proposals: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        bigint,
        string,
        string,
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        boolean
      ] & {
        id: bigint;
        title: string;
        description: string;
        creator: string;
        startTime: bigint;
        endTime: bigint;
        quorum: bigint;
        yesVotes: bigint;
        noVotes: bigint;
        abstainVotes: bigint;
        exists: boolean;
      }
    ],
    "view"
  >;

  vote: TypedContractMethod<
    [_proposalId: BigNumberish, _choice: BigNumberish],
    [void],
    "nonpayable"
  >;

  votes: TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [bigint],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "createProposal"
  ): TypedContractMethod<
    [
      _title: string,
      _description: string,
      _durationSec: BigNumberish,
      _quorum: BigNumberish
    ],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getAllProposals"
  ): TypedContractMethod<
    [],
    [
      [
        bigint[],
        string[],
        string[],
        bigint[],
        bigint[],
        bigint[],
        bigint[],
        bigint[]
      ] & {
        ids: bigint[];
        titles: string[];
        creators: string[];
        yesArr: bigint[];
        noArr: bigint[];
        abstainArr: bigint[];
        endTimes: bigint[];
        statuses: bigint[];
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getProposal"
  ): TypedContractMethod<
    [_id: BigNumberish],
    [
      [
        bigint,
        string,
        string,
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint
      ] & {
        id: bigint;
        title: string;
        description: string;
        creator: string;
        startTime: bigint;
        endTime: bigint;
        quorum: bigint;
        yesVotes: bigint;
        noVotes: bigint;
        abstainVotes: bigint;
        status: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getVote"
  ): TypedContractMethod<
    [_voter: AddressLike, _proposalId: BigNumberish],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "proposalCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "proposals"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        bigint,
        string,
        string,
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        bigint,
        boolean
      ] & {
        id: bigint;
        title: string;
        description: string;
        creator: string;
        startTime: bigint;
        endTime: bigint;
        quorum: bigint;
        yesVotes: bigint;
        noVotes: bigint;
        abstainVotes: bigint;
        exists: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "vote"
  ): TypedContractMethod<
    [_proposalId: BigNumberish, _choice: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "votes"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [bigint],
    "view"
  >;

  getEvent(
    key: "ProposalCreated"
  ): TypedContractEvent<
    ProposalCreatedEvent.InputTuple,
    ProposalCreatedEvent.OutputTuple,
    ProposalCreatedEvent.OutputObject
  >;
  getEvent(
    key: "Voted"
  ): TypedContractEvent<
    VotedEvent.InputTuple,
    VotedEvent.OutputTuple,
    VotedEvent.OutputObject
  >;

  filters: {
    "ProposalCreated(uint256,address,string,uint256,uint256,uint256)": TypedContractEvent<
      ProposalCreatedEvent.InputTuple,
      ProposalCreatedEvent.OutputTuple,
      ProposalCreatedEvent.OutputObject
    >;
    ProposalCreated: TypedContractEvent<
      ProposalCreatedEvent.InputTuple,
      ProposalCreatedEvent.OutputTuple,
      ProposalCreatedEvent.OutputObject
    >;

    "Voted(uint256,address,uint8)": TypedContractEvent<
      VotedEvent.InputTuple,
      VotedEvent.OutputTuple,
      VotedEvent.OutputObject
    >;
    Voted: TypedContractEvent<
      VotedEvent.InputTuple,
      VotedEvent.OutputTuple,
      VotedEvent.OutputObject
    >;
  };
}
