/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { ChainVotes } from "./ChainVotes";
export * as factories from "./factories";
export { ChainVotes__factory } from "./factories/ChainVotes__factory";
